### PR TITLE
Add company logo

### PR DESCRIPTION
**Pull request by ivanpanshin**
Image link: https://promo-bot.ru/media/2016/04/full-white-900.png
Company link: https://promo-bot.ai

### CODE REVIEW

**Comment by albu** [comment]
Looks like description is different from what you did. What did you want to do?

**Comment by ivanpanshin** [comment]
Hm. If that's the case, my bad. I wanted to add a company logo to readme. Since Promobot uses albumentations, I decided to send a pr to add its logo.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by albu** [comment]
Probably you specified wrong branch for this pr

**Comment by ivanpanshin** [comment]
Should I send another pr? Btw, if I remember correctly, I chose readme branch

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Dipet** [comment]
Yes you can create new PR.

Closed: Empty PR.

**Pull request closed without merging**
