### PR TITLE
Feature/random_gaze

### PR DESCRIPTION
**Pull request by CarlosUziel**
Added a new augmentation function that we use at MoonVision GmbH.

### CODE REVIEW

**Comment by BloodAxe** [comment]
@CarlosUziel Hi! Thanks for your PR. It seems there are few conflicts that prevents merging this augmentation. Can you please address these issues so that we can review the PR?

**Comment by CarlosUziel** [comment]
> @CarlosUziel Hi! Thanks for your PR. It seems there are few conflicts that prevents merging this augmentation. Can you please address these issues so that we can review the PR?

Thank you for your reply. I believe all conflicts have been resolved, please let me know if there is any of them remaining.

**Comment by albu** [comment]
```
./tests/test_functional.py:849:1: W293 blank line contains whitespace
./albumentations/augmentations/bbox_utils.py:53:1: E302 expected 2 blank lines, found 1
./albumentations/augmentations/transforms.py:106:9: F821 undefined name 'uper'
./albumentations/augmentations/functional.py:1144:1: D401 First line should be in imperative mood
./albumentations/augmentations/functional.py:1162:1: D401 First line should be in imperative mood
./albumentations/augmentations/functional.py:1176:37: E226 missing whitespace around arithmetic operator
./albumentations/augmentations/functional.py:1177:37: E226 missing whitespace around arithmetic operator
./albumentations/augmentations/functional.py:1215:1: D401 First line should be in imperative mood
```

**Comment by CarlosUziel** [comment]
> @CarlosUziel Hi! Thanks for your PR. It seems there are few conflicts that prevents merging this augmentation. Can you please address these issues so that we can review the PR?

Thanks for the heads up, all conflicts should be resolved now.

**Comment by CarlosUziel** [comment]
> ```
> ./tests/test_functional.py:849:1: W293 blank line contains whitespace
> ./albumentations/augmentations/bbox_utils.py:53:1: E302 expected 2 blank lines, found 1
> ./albumentations/augmentations/transforms.py:106:9: F821 undefined name 'uper'
> ./albumentations/augmentations/functional.py:1144:1: D401 First line should be in imperative mood
> ./albumentations/augmentations/functional.py:1162:1: D401 First line should be in imperative mood
> ./albumentations/augmentations/functional.py:1176:37: E226 missing whitespace around arithmetic operator
> ./albumentations/augmentations/functional.py:1177:37: E226 missing whitespace around arithmetic operator
> ./albumentations/augmentations/functional.py:1215:1: D401 First line should be in imperative mood
> ```

Hi, thanks. I will fix that.

**Comment by albu** [comment]
```
./albumentations/augmentations/functional.py:1144:1: D401 First line should be in imperative mood
./albumentations/augmentations/functional.py:1162:1: D401 First line should be in imperative mood
./albumentations/augmentations/functional.py:1215:1: D401 First line should be in imperative mood
```

**Comment by Dipet** [comment]
This PR is to old. If you need this functionality, please create new PR.

**Pull request closed without merging**
