### PR TITLE
Jk/rotation augmentation

### PR DESCRIPTION
**Pull request by joonkAkasha**
implementation for ICCV 2021 paper algorithm 1

https://arxiv.org/pdf/2109.13488.pdf

algorithm.py was used for testing purposes and will be removed after the PR is approved

### CODE REVIEW

**Comment by ternaus** [comment]
You can add this type of rotation to the existing rotation algorithms.

For this you need:

1. Add the desired functionality to the existing rotations transforms.
2. Write tests.
3. Make sure that everything works.

**Comment by victor1cea** [comment]
@joonkAkasha do still plan on working on this PR?

**Comment by victor1cea** [comment]
@ternaus I would assume that OP has abandoned this PR, so I could try to implement this rotation method. Could I ask you some implementation details?
Regarding point 1:
I was thinking of adding to `bbox_rotate()` a new argument `method` that can be used to choose between the "largest box" rotation method (current one) and "ellipsoid" rotation method. Would this be ok?
Regarding 2:
There is an [official repo](https://github.com/akasha-imaging/ICCV2021) that I could used to generate some test cases against.
Another thing:
`bbox_rotate()` is basically `bbox_shift_scale_rotate()`, but with no scaling and shifting. However there are 2 explicit implementations. Why not call `bbox_shift_scale_rotate()` with no scaling and shifting inside of `bbox_rotate()`?

https://github.com/albumentations-team/albumentations/blob/0d98b4f46f04db271203381742c6abe113a8f269/albumentations/augmentations/geometric/functional.py#L123-L149

https://github.com/albumentations-team/albumentations/blob/0d98b4f46f04db271203381742c6abe113a8f269/albumentations/augmentations/geometric/functional.py#L209-L229

There is even a this test case

https://github.com/albumentations-team/albumentations/blob/0d98b4f46f04db271203381742c6abe113a8f269/tests/test_functional.py#L113-L116

**Comment by Dipet** [comment]
1. Yes, looks ok to have `method` argument.
2. Its's a good idea to reuse `bbox_shift_scale_rotate` inside `bbox_rotate` :+1:

**Comment by Dipet** [comment]
Done in #1203

**Pull request closed without merging**
