### PR TITLE
Add copy paste

### PR DESCRIPTION
**Pull request by ternaus**
Fixes:

https://github.com/albumentations-team/albumentations/issues/745

https://github.com/albumentations-team/albumentations/issues/1716

https://github.com/albumentations-team/albumentations/issues/1784

https://github.com/albumentations-team/albumentations/pull/1676

https://github.com/albumentations-team/albumentations/pull/1297

https://github.com/albumentations-team/albumentations/issues/1225

https://github.com/albumentations-team/albumentations/issues/865

## Summary by Sourcery

This pull request introduces a new `CopyPaste` transformation for image augmentation, enhances the `OverlayElements` transformation, and updates the test suite to cover the new functionality. Additionally, it includes a minor update to the pre-commit configuration.

- **New Features**:
    - Introduced a new `CopyPaste` transformation for image augmentation, supporting image, mask, bounding boxes, and keypoints.
- **Enhancements**:
    - Enhanced the `OverlayElements` transformation to improve metadata handling and added an example usage in the docstring.
    - Refactored `apply_to_bboxes`, `apply_to_keypoints`, and `apply_to_masks` methods to use `List` instead of `Sequence` for type annotations.
- **Build**:
    - Updated pre-commit configuration to use mypy version v1.10.1.
- **Tests**:
    - Added tests for the new `CopyPaste` transformation to ensure correct functionality.
    - Updated existing tests to include cases for the `CopyPaste` transformation.
    - Refactored tests to handle the new metadata requirements for `OverlayElements` and `CopyPaste` transformations.

### CODE REVIEW

**Comment by ternaus** [comment]
@GeorgePearse I could implement this, the question is how to do it in a useful way.

For that I need to start training object detection models, which I am not doing right now.

=>

1. Either someone who trains object detection and uses the transform will create Pull Request.

or

2. $1000 donation and I will do it myself.

Feel free to create a pull request ;)

**Comment by GeorgePearse** [comment]
> @GeorgePearse I could implement this, the question is how to do it in a useful way.
> 
> For that I need to start training object detection models, which I am not doing right now.
> 
> =>
> 
> 1. Either someone who trains object detection and uses the transform will create Pull Request.
> 
> or
> 
> 2. $1000 donation and I will do it myself.
> 
> Feel free to create a pull request ;) 
> 

@ternaus can't argue with that. Excellent response.

I'll think about it, we have a hacky implementation internally at the min.

**Comment by ternaus** [comment]
@GeorgePearse do you have it as a part of the working training pipeline?

**Comment by GeorgePearse** [comment]
Yeah, we sort of provide an object store to the augmentation. 

Actually the more I think about this, the more I think it shouldn't be too bad to implement it cleanly and efficiently. It would require quite a lot of additional code though. The sort of thing that would maybe be best achieved via an optional additional package, which takes a COCO Json file and returns an object_store which can then be provided to the actual augmentation, so that the augmentation can still only act on one image at a time.

**Comment by GeorgePearse** [comment]
I'll try to checkout you're existing implementation. 

Ours is too tied to MMDetection currently.

**Pull request closed without merging**
