### PR TITLE
Add pytorch import

### PR DESCRIPTION
**Pull request by LightAllWorld**
Added the missing pytorch import to the __init__ file.
This addition prevents potential errors during the transform automation process.

Please review the PR, and feel free to provide any feedback. Thank you!

## Summary by Sourcery

Fix import error by adding the missing PyTorch import in the __init__.py file to ensure proper functionality of the transform automation process.

Bug Fixes:
- Add missing import for PyTorch in the __init__.py file to prevent potential errors during the transform automation process.

### CODE REVIEW

**Comment by ternaus** [comment]
@LightAllWorld 

Could you please be more specific.

1. Why do you think that pytorch dependency is missing?
2. What transform automation process you have in mind?
3. What proper functionality you have in mind, that is not in the library yet?

Your feedback would help to pick the proper priorities for the next step in the library.

**Comment by LightAllWorld** [comment]
When training an AI model, I may wish to utilize the various transformation functions provided by Albumentations. By importing everything under Albumentations with import albumentations as A, you can conveniently use transformations such as A.Resize directly. However, when it comes to converting the image into a tensor for model input, A.ToTensorV2 is not immediately accessible in the same way.

**Comment by ternaus** [comment]
Can you just do

```python
import torch
import albumentations
```
in your code?

**Comment by LightAllWorld** [comment]
yes.
This is a piece of my code.
```python
import torch
import torchvision
import albumentations as A
from albumentations.pytorch import ToTensorV2
...
```

**Comment by ternaus** [comment]
Ok, so the issue is not that torch should be imported in albumentations, bu that import in the way that you show does not work.

```python
 from albumentations.pytorch import ToTensorV2
```
will do the job

**Pull request closed without merging**
