### PR TITLE
TemplateTransform

### PR DESCRIPTION
**Pull request by akarsakov**
Add TemplateTransform which allows blending of input image with specified templates.

Refer to issue: #477

### CODE REVIEW

**Comment by akarsakov** [comment]
I missed serialization test and have to fix serialization of templates (numpy arrays to yaml). I see two options here:
1. Add custom deserialization of templates (preserving dtype)
2. Change interface for template transform and require filenames of template files.

I prefer first option, since second interface is less handy and will make testing more complicated (at least requires to store test data in repo).

**Comment by akarsakov** [comment]
I've chosen second option and made TemplateTransform accept filenames as inputs. 
In order to properly test it I introduced ImreadMock.

**Comment by Dipet** [comment]
Thank you for PR.
I think better, to mark this transformm as not serializable without custom serialization function. Look to `Lambda` for example.

**Comment by Dipet** [comment]
Also I think better get templates as images. With this approach we can get templates from some dataloader class.

**Comment by akarsakov** [comment]
Hi @Dipet,
Ok, I see. So you propose to get list of images as input? 
And are you ok with template_transform logic? Or we can assume that some augmentation could be done on DataLoader side.

**Comment by akarsakov** [comment]
Hi @Dipet,
I've made TemplateTransform non-serializable similar to Lambda. I had to rename 'lambda_transforms' argument in 'from_dict' method and marked it as deprecated.

**Comment by ternaus** [comment]
Our fault, we got distracted and forgot about your PRs. :(

@akarsakov Could you please rebase PRs on the latest master and we will work on merging them.

**Comment by akarsakov** [comment]
@ternaus No problem :) I've rebased branch.

**Review by Dipet — APPROVED** [review]

**Comment by Dipet** [comment]
Examples

```python
import random
import numpy as np
import albumentations as A
import matplotlib.pyplot as plt


def check(img: np.ndarray, templates: list, img_weight: float, template_weight: float) -> None:
    t = A.Compose(
        [
            A.Resize(512, 512),
            A.TemplateTransform(
                templates,
                img_weight=img_weight,
                template_weight=template_weight,
                template_transform=A.Compose([A.Resize(512, 512)]),
                p=1,
            ),
        ]
    )

    res = t(image=img)["image"]

    plt.figure(figsize=(15, 15))
    plt.subplot(221, title="original")
    plt.imshow(img, vmin=0, vmax=255)
    plt.subplot(222, title="template")
    plt.imshow(templates[0], vmin=0, vmax=255)
    plt.subplot(212, title=f"img_weight={img_weight} template_weight={template_weight}")
    plt.imshow(res, vmin=0, vmax=255)
    plt.show()


seed = 0
random.seed(seed)
np.random.seed(seed)

img = A.read_rgb_image("/home/dipetm/github/albumentations_examples/images/original_parrot.jpg")
templates = [A.read_rgb_image("/home/dipetm/github/albumentations_examples/notebooks/images/image_1.jpg")]

check(img, templates, 0.5, 0.5)
check(img, templates, 0.3, 0.7)
check(img, templates, 0.7, 0.3)
check(img, templates, 1, 1)
check(img, templates, 1, 2)
check(img, templates, 2, 1)
```

image
image
image
image
image
image

**Review by creafz — APPROVED** [review]

**Pull request merged**
