### PR TITLE
Pad image for large random sized crop.

### PR DESCRIPTION
**Pull request by Dipet**
#142

### CODE REVIEW

**Comment by ternaus** [comment]
I do not support these changes. Unclear and unexpected padding may be a source of bugs.

For Crops, we have an Exception. We may update it and recommend PadIfNeeded to be used before the crop function to make it more explicit.

For RandomSizedCrop we should probably make crop smaller if it fits into the proposed range of the transformation and throw an Exception otherwise.

**Comment by albu** [comment]
we need to discuss it more broader

**Comment by Dipet** [comment]
To be honest I agree with @ternaus. I think, If we need this type of transform I see 2 options how we can do this:
1. Create new transform like RandomSizedCropWithPad;
2. Add flag `pad_if_need` or `accept_large_crop` to transforms that uses `random_crop`

**Comment by albu** [comment]
yes, both options are good

**Comment by ternaus** [comment]
I would prefer second option.

We already have two `RandomSized` transforms. Would prefer to avoid generating third :)

**Comment by albu** [comment]
"RandomCrop",
    "CenterCrop",
    "RandomSizedCrop",
    "RandomResizedCrop",
    "RandomCropNearBBox",
    "RandomSizedBBoxSafeCrop",

you're too optimistic about 2 :)

**Comment by Dipet** [comment]
Too old, not relevant

**Pull request closed without merging**
