### PR TITLE
Fix random grid shuffle

### PR DESCRIPTION
**Pull request by ayasyrev**
#1625

### CODE REVIEW

**Comment by ternaus** [comment]
We also need to add test that shows that tiles are indeed shuffled.

**Review by ayasyrev — COMMENTED** [review]
Fix tests - change defaults settings at serialization, check image changed

**Review by ayasyrev — COMMENTED** [review]
Add warning if image size not dividable by grid size.
Add test that image not changed and got warning

**Review by ayasyrev — COMMENTED** [review]
rename image_shape -> height, weight

**Pull request merged**
