### PR TITLE
Eraser

### PR DESCRIPTION
**Pull request by Lemorra**
Eraser is a sub-module to synthesis a new dataset that has equal numbered of instances of different classes from an existing dataset. It requires the associated label txts in kitti format.

### CODE REVIEW

**Comment by Lemorra** [comment]
@ternaus I hope its okay to tag you here. I'm tagging you here for a request to assign a reviewer to review my merge request.

**Comment by Dipet** [comment]
Hi. Sorry for the late response. Please, remove pre-commit changes, they are not needed for your changes and they made a lot of changes in files that are not related to your target changes.
Now it is hard to analyze your changes

**Comment by Lemorra** [comment]
@Dipet, I request you to explain the label "wontfix". Does this mean that this feature is of no help to albumentations repo and won't be merged to the master?

**Comment by Dipet** [comment]
Hi. sorry that I did not write explanation.
Need to remove `sampleImages` directory. We decided do not store any binary data inside this repository. For examples and documentation we hav this repository https://github.com/albumentations-team/albumentations_examples4
The current implementaion does not inherit from `ImageOnlyTransform` or `DuatlTransorm` and can not work inside `Compose`. For these reason we can not now aprove this PR.

**Comment by Lemorra** [comment]
@Dipet , sorry for the late update. I have tried using the image only transform class for creating a new class named "MetaData" for the eraser feature. I have implemented some methods to it. Do review it and let me know if those methods are correct or not. Also I will be removing those images in my next commit once I get a reply from you regarding the methods of the new class.

**Comment by Lemorra** [comment]
@Dipet, do review my implementation of the feature that can be run with Compose. Your inputs will help me progress in getting the feature implemented in albumentations

**Comment by ternaus** [comment]
It does not look like a feature that will be added in the near future.

**Pull request closed without merging**
