### PR TITLE
Fixes the pre-commit

### LINKED ISSUE #1367: Pre-commit flake8 link fails
## 🐛 Bug

Flake8 took down the gitlab repository in favor of github, so the flake8 link fails which makes pre-commit fails.

## To Reproduce

1. Run the pre-commit

## Expected behavior

Succesfully running pre-commit

## Environment

Master branch

### PR DESCRIPTION
**Pull request by onurtore**
Fixes #1367

### CODE REVIEW

**Comment by onurtore** [comment]
Hi @Dipet,
I inspected the failures, they do not like comes from my side. Can you eloborate?

**Comment by Dipet** [comment]
I am trying to fix them in #1370

**Review by Dipet — APPROVED** [review]

**Comment by onurtore** [comment]
Hi! @Dipet,
It is little bit out of the topic but, is the design pattern for the communication between functional.py and transforms.py files has a specific name? transforms.py functions (Such as RandomShadow) calls the transforms functions. It is very interesting and cool approach for a newbie like me, I would love to learn more.

**Comment by Dipet** [comment]
I do not know if this approach has some name or not. We copied this aproach from torchvision.transforms https://pytorch.org/vision/0.9/transforms.html

**Comment by onurtore** [comment]
Thanks!

**Pull request merged**
